"""
Complete Star Citizen ship roster — used for /add-ship autocomplete.
"""

SHIPS: list[str] = [
    "RSI Bengal Carrier",
    "Aegis Javelin",
    "Aegis Idris-M",
    "Aegis Idris-P",
    "Aegis Idris-P Wikelo War Special",
    "Aegis Hammerhead",
    "Aegis Hammerhead 2949 Best In Show Edition",
    "RSI Perseus",
    "RSI Polaris",
    "Crusader A2 Hercules Starlifter",
    "Crusader A2 Hercules Starlifter Wikelo War Special",
    "Crusader M2 Hercules Starlifter",
    "MISC Starfarer Gemini",
    "MISC Starlancer TAC",
    "MISC Starlancer TAC Wikelo War Special",
    "Aegis Reclaimer",
    "Black Kite",
    "Pride of Arliss",
    "Aegis Reclaimer 2949 Best In Show Edition",
    "Aegis Reclaimer Teach's Special",
    "Drake Caterpillar",
    "Drake Caterpillar Pirate",
    "KRF Inmate Transport",
    "Drake Caterpillar 2949 Best In Show Edition",
    "Origin 890 Jump",
    "Anvil Carrack",
    "Anvil Carrack Expedition",
    "Crusader C2 Hercules Starlifter",
    "MISC Hull C",
    "MISC Starfarer",
    "MISC Starfarer Teach's Special",
    "MISC Starlancer MAX",
    "MISC Starlancer MAX Wikelo Work Special",
    "Origin 600i",
    "Origin 600i 2951 BIS",
    "Origin 600i Executive Edition",
    "Origin 600i Touring",
    "Aegis Redeemer",
    "Aegis Retaliator",
    "Aegis Vanguard Warden",
    "Aegis Vanguard Harbinger",
    "Aegis Vanguard Hoplite",
    "Aegis Vanguard Sentinel",
    "Anvil F8A Lightning",
    "Anvil F8C Lightning",
    "Anvil F8C Lightning Wikelo War Special",
    "Anvil F8C Lightning Wikelo Sneak Special",
    "Anvil F8C Lightning Executive Edition",
    "F8C Lightning PYAM Exec",
    "Anvil Paladin",
    "Anvil Valkyrie",
    "Anvil Valkyrie Liberator",
    "Drake Corsair",
    "Corsair PYAM Exec",
    "Esperia Prowler",
    "Esperia Prowler Utility",
    "Esperia Prowler Utility Wikelo Work Special",
    "Mirai Guardian",
    "Mirai Guardian Wikelo War Special",
    "Mirai Guardian MX",
    "Mirai Guardian MX Wikelo War Special",
    "Mirai Guardian QI",
    "Mirai Guardian QI Wikelo Special",
    "RSI Apollo Medivac",
    "RSI Apollo Triage",
    "RSI Apollo Triage Collector Stealth",
    "RSI Constellation Andromeda",
    "RSI Constellation Aquila",
    "RSI Hermes",
    "Esperia Stinger",
    "Vanduul Stinger",
    "Argo MOLE",
    "Argo MOLE Teach's Special",
    "Argo MOTH",
    "Anvil Terrapin",
    "Anvil Terrapin Medic",
    "Anvil Terrapin Medic Wikelo Savior Special",
    "Crusader Mercury Star Runner",
    "RSI Constellation Phoenix",
    "RSI Constellation Phoenix Emerald",
    "RSI Constellation Taurus",
    "RSI Constellation Taurus Wikelo War Special",
    "RSI Zeus Mk II CL",
    "RSI Zeus Mk II ES",
    "RSI Zeus Mk II ES Wikelo Work Special",
    "Aegis Sabre Firebird",
    "Aegis Sabre Firebird Wikelo War Special",
    "Anvil Asgard",
    "Anvil Asgard Wikelo War Special",
    "Anvil Gladiator",
    "Anvil F7A Hornet Mk I",
    "Anvil F7A Hornet Mk II",
    "Hornet F7A Mk II PYAM Exec",
    "Anvil F7C Hornet Mk I",
    "Anvil F7C-M Super Hornet Mk I",
    "Anvil F7C-M Hornet Heartseeker Mk I",
    "Anvil F7C-M Super Hornet Mk II",
    "Anvil F7C-M Hornet Heartseeker Mk II",
    "Anvil F7C-R Hornet Tracker Mk I",
    "Anvil F7C-S Hornet Ghost Mk I",
    "Anvil F7C-S Hornet Ghost Mk II",
    "Anvil F7C Hornet Mk II",
    "Anvil F7C Hornet Wildfire Mk I",
    "Anvil F7 Hornet Mk Wikelo",
    "Anvil Hurricane",
    "Banu Defender",
    "Crusader Ares Star Fighter Inferno",
    "Crusader Ares Star Fighter Inferno Wikelo War Special",
    "Crusader Ares Star Fighter Ion",
    "Crusader Ares Star Fighter Ion Wikelo Sneak Special",
    "Drake Cutlass Black",
    "Cutlass Black PYAM Exec",
    "Drake Cutlass 2949 Best In Show Edition",
    "Drake Cutlass Steel",
    "MISC Freelancer MIS",
    "RSI Mantis",
    "RSI Meteor",
    "RSI Meteor PYAM Exec",
    "RSI Meteor Wikelo Sneak Special",
    "Esperia Glaive",
    "Vanduul Glaive",
    "Vanduul Scythe",
    "Aopoa San'tok.yāi",
    "Drake Golem",
    "Drake Golem Wikelo Work Special",
    "Drake Golem OX",
    "Drake Golem Teach's Special",
    "Drake Herald",
    "Drake Vulture",
    "Drake Vulture Teach's Special",
    "MISC Prospector",
    "MISC Prospector Wikelo Work Special",
    "Argo RAFT",
    "Argo RAFT Wikelo Work Special",
    "Drake Cutlass Blue",
    "Drake Cutlass Red",
    "MISC Freelancer",
    "MISC Freelancer DUR",
    "MISC Freelancer MAX",
    "MISC Hull A",
    "Origin 400i",
    "Aegis Sabre",
    "Aegis Sabre Comet",
    "Aegis Sabre Raven",
    "Anvil F7C-R Hornet Tracker Mk II",
    "Aegis Avenger Titan",
    "Aegis Avenger Titan Renegade",
    "Aegis Avenger Warlock",
    "Aegis Gladius",
    "Aegis Gladius Dunlevy",
    "Aegis Gladius Pirate",
    "Aegis Gladius Valiant",
    "Anvil Arrow",
    "Anvil Hawk",
    "Drake Buccaneer",
    "Esperia Talon",
    "Esperia Talon Shrike",
    "Grey's Shiv",
    "Kruger L-21 Wolf",
    "Kruger L-21 Wolf Wikelo War Special",
    "Kruger L-21 Wolf Wikelo Sneak Special",
    "Kruger L-22 Alpha Wolf",
    "MISC Reliant Tana",
    "RSI Scorpius",
    "RSI Scorpius Antares",
    "RSI Scorpius Wikelo Sneak Special",
    "Esperia Blade",
    "Vanduul Blade",
    "Aopoa Khartu-al",
    "Aegis Sabre Peregrine",
    "Aegis Sabre Peregrine Wikelo Speedy Special",
    "Argo SRV",
    "Gatac Syulen",
    "Syulen PYAM Exec",
    "MISC Fortune",
    "MISC Fortune Wikelo Special",
    "MISC Fortune Teach's Special",
    "RSI Salvation",
    "C.O. Nomad",
    "C.O. Nomad Teach's Special",
    "Crusader Intrepid",
    "Crusader Intrepid Wikelo Work Special",
    "Crusader A1 Spirit",
    "Crusader C1 Spirit",
    "Crusader C1 Spirit Wikelo Special",
    "Drake Clipper",
    "Drake Cutter",
    "Drake Cutter Rambler",
    "Drake Cutter Scout",
    "MISC Reliant Kore",
    "MISC Reliant Mako",
    "MISC Reliant Sen",
    "Origin 300i",
    "Origin 315p",
    "Origin 325a",
    "Origin 350r",
    "Origin 85X Limited",
    "Aegis Avenger Stalker",
    "Aegis Eclipse",
    "Mirai Fury",
    "Mirai Fury MX",
    "Mirai Razor",
    "Mirai Razor EX",
    "Aopoa Nox",
    "Aopoa Nox Wikelo Special",
    "Aopoa Nox Kue",
    "Anvil C8R Pisces Rescue",
    "Anvil C8X Pisces Expedition",
    "Anvil C8 Pisces",
    "Argo MPUV Cargo",
    "Argo MPUV Tractor",
    "Argo MPUV Personnel",
    "C.O. HoverQuad",
    "C.O. Mustang Alpha",
    "C.O. Mustang CitizenCon 2948 Edition",
    "C.O. Mustang Beta",
    "C.O. Mustang Delta",
    "C.O. Mustang Gamma",
    "C.O. Mustang Omega",
    "Drake Dragonfly",
    "Drake Dragonfly Star Kitten",
    "Drake Dragonfly Yellowjacket",
    "Mirai Pulse",
    "Mirai Pulse Wikelo Special",
    "Origin 100i",
    "Origin 125a",
    "Origin 135c",
    "Origin X1",
    "Origin X1 Force",
    "Origin X1 Velocity",
    "RSI Aurora Mk I CL",
    "RSI Aurora Mk I ES",
    "RSI Aurora Mk I LN",
    "RSI Aurora Mk I LX",
    "RSI Aurora Mk I MR",
    "Kruger P-52 Merlin",
    "Kruger P-72 Archimedes",
    "Kruger P-72 Archimedes Emerald",
    "Mirai Fury LX",
    "Mirai Razor LX",
    "Mirai Pulse LX",
    "Origin M50 Interceptor",
]

# Build a lowercased search index for fast autocomplete
_SHIPS_LOWER: list[tuple[str, str]] = [(s.lower(), s) for s in SHIPS]


def search_ships(partial: str) -> list[str]:
    """Return up to 25 ship names whose lowercased form contains `partial`."""
    needle = partial.lower()
    return [original for lower, original in _SHIPS_LOWER if needle in lower][:25]
